name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Docker
      run: |
        # Remove any existing Docker packages to avoid conflicts
        sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
        sudo apt-get autoremove -y
        
        # Install prerequisites
        sudo apt-get update
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg \
          lsb-release
        
        # Add Docker's official GPG key
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        
        # Set up the stable repository
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        
        # Install Docker Engine
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        
        # Start Docker service
        sudo systemctl start docker
        sudo systemctl enable docker
        
        # Add runner user to docker group
        sudo usermod -aG docker $USER
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    - name: Correct Project Structure
      id: correct-project-structure
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Correct Project Structure
        setup-command: ''
        command: "./.csse6400/bin/validate_structure.sh"
        timeout: 5
        max-score: 25
    - name: Clean Git Repository
      id: clean-git-repository
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Clean Git Repository
        setup-command: ''
        command: "./.csse6400/bin/clean_repository.sh"
        timeout: 5
        max-score: 25
    - name: Docker
      id: docker
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Docker
        setup-command: ''
        command: "./.csse6400/bin/docker.sh"
        timeout: 8
        max-score: 25
    - name: Docker Compose
      id: docker-compose
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Docker Compose
        setup-command: ''
        command: "./.csse6400/bin/docker-compose.sh"
        timeout: 10
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CORRECT-PROJECT-STRUCTURE_RESULTS: "${{steps.correct-project-structure.outputs.result}}"
        CLEAN-GIT-REPOSITORY_RESULTS: "${{steps.clean-git-repository.outputs.result}}"
        DOCKER_RESULTS: "${{steps.docker.outputs.result}}"
        DOCKER-COMPOSE_RESULTS: "${{steps.docker-compose.outputs.result}}"
      with:
        runners: correct-project-structure,clean-git-repository,docker,docker-compose
